name: PR Coverage Check

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Check coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: '**/target/site/jacoco/jacoco.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 90

      - name: Fail workflow if coverage is low
        if: ${{ steps.jacoco.outputs.coverage-overall < 90 }}
        run: echo "❌ Coverage below 90%" && exit 1