name: Maven Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Generate coverage report
        run: mvn test jacoco:report

      - name: Check coverage threshold
        uses: 5monkeys/code-coverage-action@v1
        with:
          coverage-files: target/site/jacoco/jacoco.xml
          minimum-coverage: 90
          fail-on-coverage-decrease: true
